### ISSUE TITLE
Check out nbind

### ISSUE THREAD

**Issue by jjrv** [DAB0mB/node-distance-addon#1]
[nbind](github.com/charto/nbind#readme) is a toolkit that automates the module registration, gyp file creation, type conversion and as a bonus, it allows compiling the same code for asm.js and generating TypeScript definitions with no extra work. Doing a really simple test addon like the synchronous distance calculation shouldn't take more than a few minutes following the quick start instructions. Maybe you could test it and add a link from the tutorial?

**Comment by DAB0mB** [comment]
@jjrv It looks great! I'm planning to write another tutorial but this time it will be running on the client and I will be using Emscripten. I will definitely check that out.

**Comment by jjrv** [comment]
There's another tutorial here (saw it on EchoJS just now):

https://blog.risingstack.com/writing-native-node-js-modules

I took the liberty of porting it to nbind, you can compare them:

https://github.com/peteyy/native-addon-example/issues/1

Note that after porting, it also works on asm.js (when using Emscripten).

If you want, I could port your example too, but it would be quite similar to the nbind quick start instructions and that other ported example.

**Comment by DAB0mB** [comment]
Closing, I don't wanna spam the issues section
