### ISSUE TITLE
in views/step2.md seems to be an error

### ISSUE THREAD

**Issue by eisneim** [DAB0mB/node-distance-addon#2]
Hi, thanks for this great tutorial on create nodejs cpp addon!

in this markdown, 
https://github.com/DAB0mB/node-distance-addon/blob/master/.tortilla/manuals/views/step2.md
add test code block appears twice, the second one is should show reader "NAN_METHOD(CalculateSync)" instead.

**Comment by DAB0mB** [comment]
@eisneim Thanks! This is actually a problem in the template, not the view, since this is an auto-generated tutorial. I will fix this asap and let you know.

**Comment by DAB0mB** [comment]
@eisneim Fixed it! See https://github.com/DAB0mB/node-distance-addon/blob/master/.tortilla/manuals/views/step2.md#step-210-add-return-value-to-calculatesync-method

**Comment by eisneim** [comment]
👍
